Laboratory work 1.
PyTorch Fundamentals Exercises
Completed: Halka Artur

Variant: #3

Task 1. Create a random tensor

Create a random tensor that mimics a batch of images intended for a convolutional neural network. Generate a tensor with shape (32, 3, 64, 64), where 32 represents the batch size, 3 the color channels, and 64 x 64 the spatial dimensions of each image.
After generating this tensor, calculate the mean and variance over the batch or channel dimensions to simulate data normalization steps. This task is an excellent introduction to handling high-dimensional data and understanding how deep learning models process image data.

In [1]:
import torch
import numpy as np

# Ensure reproducibility
torch.manual_seed(42)

In [5]:
batch_size = 32
channels = 3
height = 64
width = 64

images = torch.rand(batch_size, channels, height, width)

print("Tensor shape:", images.shape)
print("Tensor dtype:", images.dtype)
print("Tensor device:", images.device)

mean_over_batch = torch.mean(images, dim=0)
var_over_batch = torch.var(images, dim=0)

print("Mean over batch shape:", mean_over_batch.shape)
print("Variance over batch shape:", var_over_batch.shape)

Tensor shape: torch.Size([32, 3, 64, 64])
Tensor dtype: torch.float32
Tensor device: cpu
Mean over batch shape: torch.Size([3, 64, 64])
Variance over batch shape: torch.Size([3, 64, 64])


Task 2. Simple matrix multiplication

Variant 3: Create two square tensors of shape (10, 10) using PyTorch’s random functions and perform matrix multiplication between them. After obtaining the product, calculate the trace of the resulting matrix to explore the relationship between matrix multiplication and trace calculation. This exercise serves as a practical demonstration of how linear algebra concepts like trace are applied in neural network operations and regularization techniques. Technical note: Use torch.rand for tensor creation, torch.mm for multiplication, and torch.trace to compute the trace of the product.

In [9]:
t1 = torch.rand(10, 10)
t2 = torch.rand(10, 10)

product = torch.mm(t1, t2)
trace_value = torch.trace(product)

print("Trace of the product:", trace_value)

Trace of the product: tensor(23.1938)


Task 3. The use of CPU vs. GPU

Variant 3: Set a specific random seed for both CPU and GPU computations using torch.manual_seed and torch.cuda.manual_seed_all. Create identical random tensors on the CPU and GPU with shape (6, 6), then compute the elementwise sine of both tensors. Finally, compare the outputs to verify that operations yield consistent results across devices.

Technical note: Use torch.manual_seed(seed) for CPU and torch.cuda.manual_seed_all(seed) for GPU seeding, torch.sin() for elementwise sine computation, and .to(device) for device transfers.

In [ ]:
print("CUDA available:", torch.cuda.is_available()) # cuda only for nvidia gpu
print("Number of GPUs:", torch.cuda.device_count())

isCudaAvailable = torch.cuda.is_available()

seed = 10563
torch.manual_seed(seed)

if isCudaAvailable:
    torch.cuda.manual_seed_all(seed)

device_cpu = torch.device("cpu")
device_gpu = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

tensor_cpu = torch.rand(6, 6, device=device_cpu)
tensor_gpu = torch.rand(6, 6, device=device_gpu)

sin_cpu = torch.sin(tensor_cpu)
sin_gpu = torch.sin(tensor_gpu)

# bring GPU result back to CPU for comparison
sin_gpu_cpu = sin_gpu.to("cpu")

print("CPU tensor:\n", tensor_cpu)
print("GPU tensor:\n", tensor_gpu)
print("Sine CPU:\n", sin_cpu)
print("Sine GPU:\n", sin_gpu_cpu)
print("Are CPU and GPU results identical?", torch.allclose(sin_cpu, sin_gpu_cpu))

CUDA available: False
Number of GPUs: 0
CPU tensor:
 tensor([[0.4330, 0.5607, 0.6751, 0.2305, 0.0071, 0.7178],
        [0.6273, 0.9851, 0.3407, 0.2159, 0.9081, 0.7426],
        [0.1403, 0.7092, 0.9116, 0.1814, 0.0389, 0.1259],
        [0.2064, 0.6312, 0.7658, 0.6809, 0.1328, 0.1077],
        [0.5720, 0.0909, 0.4912, 0.0052, 0.1153, 0.7015],
        [0.9111, 0.3757, 0.0073, 0.9394, 0.6594, 0.5199]])
GPU tensor:
 tensor([[0.1101, 0.5478, 0.9251, 0.0544, 0.8984, 0.4432],
        [0.4341, 0.3039, 0.0454, 0.9369, 0.2725, 0.3259],
        [0.8238, 0.2240, 0.7852, 0.2477, 0.8415, 0.9495],
        [0.9093, 0.7787, 0.6682, 0.9303, 0.2836, 0.7990],
        [0.4814, 0.3306, 0.3378, 0.9359, 0.2905, 0.8677],
        [0.2817, 0.0334, 0.4247, 0.3907, 0.4950, 0.2304]])
Sine CPU:
 tensor([[0.4196, 0.5318, 0.6250, 0.2284, 0.0071, 0.6577],
        [0.5869, 0.8333, 0.3341, 0.2143, 0.7883, 0.6762],
        [0.1398, 0.6512, 0.7905, 0.1804, 0.0389, 0.1256],
        [0.2050, 0.5901, 0.6931, 0.6295, 0.1324, 0.

Task 4. Processing a tensor

Variant 3: Create a random tensor with shape (8, 8) and process it by applying thresholding. Set values above a threshold of 0.5 to 1 and those equal to or below 0.5 to 0. Print the original tensor alongside the thresholded result to illustrate how such operations can be used in segmentation tasks or binary classification preprocessing.

Technical note: Use torch.where(tensor > 0.5, torch.tensor(1.0), torch.tensor(0.0)) for thresholding, and ensure that the tensor’s data type is compatible with the operation.

In [7]:
tensor = torch.rand(8,8)
print("Original tensor:\n", tensor)

thresholded = torch.where(tensor > 0.5, torch.tensor(1.0), torch.tensor(0.0))
print("\nThresholded tensor (0.5 cutoff):\n", thresholded)

Original tensor:
 tensor([[6.9445e-01, 8.7432e-01, 7.7577e-01, 2.0663e-01, 8.1669e-01, 5.0319e-01,
         3.2871e-01, 6.1576e-01],
        [7.1361e-01, 5.5633e-01, 6.1995e-01, 2.2927e-01, 1.6964e-01, 9.7305e-01,
         5.5834e-01, 9.5323e-01],
        [5.0982e-01, 6.0439e-01, 1.9651e-01, 4.0836e-01, 2.1100e-05, 7.7952e-02,
         1.9776e-02, 3.6351e-01],
        [8.0180e-01, 5.1341e-02, 6.6270e-01, 4.7796e-01, 6.3972e-01, 1.3395e-01,
         4.7998e-01, 8.2897e-01],
        [8.1330e-01, 3.1234e-01, 1.8266e-01, 2.0200e-01, 3.5900e-01, 6.2962e-02,
         6.6633e-01, 8.5268e-01],
        [2.5811e-02, 1.8186e-02, 5.6780e-01, 3.8950e-02, 4.6044e-01, 5.7205e-01,
         4.0108e-01, 1.7061e-01],
        [2.2426e-01, 1.9721e-01, 7.3944e-02, 1.3735e-01, 3.7446e-02, 7.5095e-01,
         3.6927e-01, 2.9620e-01],
        [9.6121e-01, 6.8093e-01, 9.4110e-01, 8.8448e-01, 3.2118e-01, 4.5555e-01,
         3.1799e-01, 8.6886e-01]])

Thresholded tensor (0.5 cutoff):
 tensor([[1., 1., 1., 0., 1

Task 5. Advancing with a tensor

Variant 3: Create a random tensor of shape (3, 4, 5) to simulate multi-dimensional data. Reshape the tensor into a two-dimensional tensor of shape (12, 5) and then compute the sum across the rows to reduce it to a one-dimensional tensor. Print both the reshaped tensor and the resulting reduced tensor. This exercise reinforces the concepts of reshaping and reduction, which are essential when adapting data for fully connected layers in deep neural networks.

Technical note: Use tensor.view() or tensor.reshape() for reshaping and torch.sum(tensor, dim=0) for the reduction operation.

In [ ]:
tensor = torch.rand(3, 4, 5)
print("Original tensor (3, 4, 5):\n", tensor)
print("\nShape:", tensor.shape)


reshaped = tensor.view(12, 5)
print("\nReshaped tensor (12, 5):\n", reshaped)
print("Shape:", reshaped.shape)

#  to 1D tensor
reduced = torch.sum(reshaped, dim=0)
print("\nReduced tensor (sum across rows):\n", reduced)
print("Shape:", reduced.shape)

Original tensor (3, 4, 5):
 tensor([[[0.0983, 0.2603, 0.4705, 0.7630, 0.5536],
         [0.1147, 0.5829, 0.0722, 0.5215, 0.6885],
         [0.9629, 0.1533, 0.6768, 0.9082, 0.3961],
         [0.5545, 0.8804, 0.2933, 0.7090, 0.9318]],

        [[0.0406, 0.7034, 0.5812, 0.1445, 0.9546],
         [0.2474, 0.2870, 0.6944, 0.3991, 0.9643],
         [0.9560, 0.2953, 0.1077, 0.3896, 0.9138],
         [0.4034, 0.8036, 0.9514, 0.7494, 0.9325]],

        [[0.9170, 0.2916, 0.7152, 0.4155, 0.7319],
         [0.5343, 0.8407, 0.5861, 0.4805, 0.0488],
         [0.6642, 0.1544, 0.3996, 0.8838, 0.4349],
         [0.3180, 0.0965, 0.5750, 0.1016, 0.5288]]])

Shape: torch.Size([3, 4, 5])

Reshaped tensor (12, 5):
 tensor([[0.0983, 0.2603, 0.4705, 0.7630, 0.5536],
        [0.1147, 0.5829, 0.0722, 0.5215, 0.6885],
        [0.9629, 0.1533, 0.6768, 0.9082, 0.3961],
        [0.5545, 0.8804, 0.2933, 0.7090, 0.9318],
        [0.0406, 0.7034, 0.5812, 0.1445, 0.9546],
        [0.2474, 0.2870, 0.6944, 0.3991, 0.9643